POST http://localhost:8001/products HTTP/1.1
Content-Type: application/json

{
	"name": "Ventilador Arno",
	"price": 568.40
}

###

GET http://localhost:8001/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDcyNjk3NzQsIm5hbWUiOiJMYWlvbiBDb3JjaW5vIiwic3ViIjoiMzI3MGNmMWMtOWQ5NC00MmZhLWE2YzAtOGM4NTUwMmJiYTQ1In0.mA_CrcnAzDAJeQhk1QtLsHtBgBQJQFyQ5zsI3-PRNKk

###

GET http://localhost:8001/products/6d5e10f3-83ec-497e-b045-b0867cac7c3d HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8001/products/5802ec0a-a33f-41d3-970c-db6cf915ac10 HTTP/1.1
Content-Type: application/json

{
  "price": 225.30
}

###

DELETE http://localhost:8001/products/a5166585-b826-44ee-8d6d-ecb32bc830f8 HTTP/1.1
Content-Type: application/json

###